# Generated by Django 4.0.5 on 2022-07-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('about', models.CharField(max_length=2000, null=True, verbose_name='About')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
