# Generated by Django 4.0.5 on 2022-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_opening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('about', models.TextField()),
                ('author', models.CharField(max_length=100, null=True, verbose_name='Author')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
